# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/CodeField_C/tlpi

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/CodeField_C/tlpi

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/CodeField_C/tlpi/CMakeFiles /root/CodeField_C/tlpi//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/CodeField_C/tlpi/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tlpi_lib

# Build rule for target.
tlpi_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tlpi_lib
.PHONY : tlpi_lib

# fast build rule for target.
tlpi_lib/fast:
	$(MAKE) $(MAKESILENT) -f lib/CMakeFiles/tlpi_lib.dir/build.make lib/CMakeFiles/tlpi_lib.dir/build
.PHONY : tlpi_lib/fast

#=============================================================================
# Target rules for targets named signal_functions

# Build rule for target.
signal_functions: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 signal_functions
.PHONY : signal_functions

# fast build rule for target.
signal_functions/fast:
	$(MAKE) $(MAKESILENT) -f signals/CMakeFiles/signal_functions.dir/build.make signals/CMakeFiles/signal_functions.dir/build
.PHONY : signal_functions/fast

#=============================================================================
# Target rules for targets named sig_sender

# Build rule for target.
sig_sender: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sig_sender
.PHONY : sig_sender

# fast build rule for target.
sig_sender/fast:
	$(MAKE) $(MAKESILENT) -f signals/CMakeFiles/sig_sender.dir/build.make signals/CMakeFiles/sig_sender.dir/build
.PHONY : sig_sender/fast

#=============================================================================
# Target rules for targets named sig_receiver

# Build rule for target.
sig_receiver: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sig_receiver
.PHONY : sig_receiver

# fast build rule for target.
sig_receiver/fast:
	$(MAKE) $(MAKESILENT) -f signals/CMakeFiles/sig_receiver.dir/build.make signals/CMakeFiles/sig_receiver.dir/build
.PHONY : sig_receiver/fast

#=============================================================================
# Target rules for targets named sig_ignore

# Build rule for target.
sig_ignore: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sig_ignore
.PHONY : sig_ignore

# fast build rule for target.
sig_ignore/fast:
	$(MAKE) $(MAKESILENT) -f signals/CMakeFiles/sig_ignore.dir/build.make signals/CMakeFiles/sig_ignore.dir/build
.PHONY : sig_ignore/fast

#=============================================================================
# Target rules for targets named my_abort

# Build rule for target.
my_abort: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 my_abort
.PHONY : my_abort

# fast build rule for target.
my_abort/fast:
	$(MAKE) $(MAKESILENT) -f signals/CMakeFiles/my_abort.dir/build.make signals/CMakeFiles/my_abort.dir/build
.PHONY : my_abort/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... my_abort"
	@echo "... sig_ignore"
	@echo "... sig_receiver"
	@echo "... sig_sender"
	@echo "... signal_functions"
	@echo "... tlpi_lib"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

